name: DROPOUT
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.19
  - pip
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - polars
  - scikit-learn
  - scipy
  - tqdm
  - seaborn
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu130
    - torch
    - torchvision    